spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/plantrowth;
    username: sa
    password:
      driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
  profiles:
    include:
      - aws
      - credentials
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


logging:
  level:
    org.hibernate.SQL: debug