language: java
jdk:
  - openjdk11

branches:
  only:
    - main

before_script:
  - cd back-end/plantrowth
  - chmod +x gradlew

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

notifications:
  email:
    recipitents:
      - xldk78@gmail.com
