language: java
jdk:
  - openjdk11

branches:
  only:
    - main



cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "cd back-end/plantrowth && ./gradlew clean build"

notifications:
  email:
    recipitents:
      - xldk78@gmail.com
